python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n25_mcl_256 --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n25_mcl_256_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n25_mcl_1024 --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n25_mcl_1024_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n50_mcl_256 --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n50_mcl_256_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n50_mcl_1024 --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n50_mcl_1024_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n100_mcl_256 --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n100_mcl_256_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n100_mcl_1024 --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n100_mcl_1024_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n25_mcl_256_quantized --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n25_mcl_256_quantized_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n50_mcl_256_quantized --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n50_mcl_256_quantized_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n100_mcl_256_quantized --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n100_mcl_256_quantized_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_aime_n89_mcl_256 --prompt_file ../tasks/aime/aime_eval_dataset.jsonl --output_file phi_outputs/phi_aime_n89_mcl_256_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_aime_n89_mcl_1024 --prompt_file ../tasks/aime/aime_eval_dataset.jsonl --output_file phi_outputs/phi_aime_n89_mcl_1024_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_countdown_n100_mcl_256_pretrained --prompt_file ../tasks/countdown/countdown_eval_dataset_phi.jsonl --output_file phi_outputs/phi_countdown_n100_mcl_256_pretrained_outputs.jsonl
python query_model.py --model microsoft/Phi-3.5-mini-instruct --adapter_repo Infernaught/phi_aime_n89_mcl_256_pretrained --prompt_file ../tasks/aime/aime_eval_dataset.jsonl --output_file phi_outputs/phi_aime_n89_mcl_256_pretrained_outputs.jsonl


